quarkus.http.port=8080

# CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=${CORS_ORIGINS:*}
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Accept,Authorization,Content-Type,X-Requested-With

# Azure Blob Storage
azure.storage.account-name=${AZURE_STORAGE_ACCOUNT_NAME:stfirmademo}
azure.storage.container=${AZURE_STORAGE_CONTAINER:documents}

# WebAuthn / FIDO2 real
# RP ID = host SIN https://
webauthn.rp.id=${WEBAUTHN_RP_ID:web-firma-demo-dheweb0cpg6djek.westcentralus-01.azurewebsites.net}
webauthn.rp.name=${WEBAUTHN_RP_NAME:Motor de Firma Electronica Demo}
# Origin = URL completa del frontend SIN slash final
webauthn.rp.origin=${WEBAUTHN_RP_ORIGIN:https://web-firma-demo-dheweb0cpg6djek.westcentralus-01.azurewebsites.net}
webauthn.ceremony-ttl-seconds=${WEBAUTHN_CEREMONY_TTL_SECONDS:300}
